#注意每个配置项“：”后面必须有一个空格
#服务配置
server:
  #端口号
  port: 18018
  servlet:
    #应用访问路径
    context-path: /

spring:
 cloud:
  consul:
    #微服务注册中心地址
    host: 192.168.0.116
    port: 8500
    discovery:
     ipAddress: 192.168.0.116
     register: false

##### 多数据源配置 #####
 datasource:
  dynamic:
   primary: oracle-chd
#oracle 数据源配置
   datasource:
    oracle-chd:
     username: chd
     password: citms
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@192.168.10.113:1521:orcl
    oracle-zhzepp:
     username: zhzepp
     password: citms
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@192.168.10.113:1521:orcl

#librA 数据源配置
    librA-tjeppv5:
     username: tjeppv5
     password: citms@123
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://192.168.0.147:25308/tjeppv5
#mysql 数据源配置
    mysql-eppv5-dev:
     username: root
     password: citms
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.0.40:3306/eppv5_dev?serverTimezone=UTC&Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    mariaDB:
     url: jdbc:mysql://192.168.0.90:3306/bookstackapp?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
     username: bookstack
     password: yourdbpass
     driver-class-name: com.mysql.jdbc.Driver
#日志配置
database:
 #显示spl性能信息
 showPerformance: false

#日志级别配置
logging:
 level:
  com.citms.dao: debug
